module.exports = {
   body : {
    data :[
        {
            "cnpj": "76279534-5",
            "codigo_posto": "76279534-5",
            "nome": "Musil Comercial",
            "os": 66284230,
            "sua_os": "66284230",
            "descricao_tipo_atendimento": "Garantia",
            "data_abertura": "17/05/2024",
            "defeito_reclamado_descricao": "rotor quemado",
            "data_digitacao": "17/05/2024",
            "data_conserto": null,
            "consumidor_fone_comercial": null,
            "consumidor_email": "jorherrera87@gmail.com",
            "consumidor_endereco": "CAPITAN WOD",
            "consumidor_numero": "4545",
            "consumidor_bairro": "",
            "consumidor_complemento": "",
            "consumidor_cep": "",
            "consumidor_cidade": "SAN FELIPE",
            "consumidor_estado": "VA",
            "data_fechamento": null,
            "os_reincidente": null,
            "referencia": "DUC357",
            "descricao": "CORTADORA DE CERAMICOS 8",
            "serie": "S987654321",
            "data_fabricacao": null,
            "defeito_reclamado": "NO GIRA EL ELEMENTO DE CORTE",
            "defeito_constatado": null,
            "solucao": null,
            "consumidor_nome": "ANTONIO CRISOSTOMO",
            "consumidor_fone": "9999999999",
            "consumidor_cpf": "90423673",
            "revenda": "CEFERINO ARTURO SEPULVEDA TORO",
            "nota_fiscal": "00000003",
            "data_nf": "01/02/2024",
            "status_os": "Aguardando Peças",
            "local_reparo": null,
            "dias_aberto": 6,
            "hd_chamado": null,
            "data_atendimento_callcenter_resolvido": null,
            "data_abertura_atendimento": null,
            "idPedido": 49091286,
            "direccion": "SANTA ROSA 1508-1510"
        },
        {
            "cnpj": "76279534-5",
            "codigo_posto": "76279534-5",
            "nome": "Musil Comercial",
            "os": 66284231,
            "sua_os": "66284231",
            "descricao_tipo_atendimento": "Garantia",
            "data_abertura": "17/05/2024",
            "defeito_reclamado_descricao": "ENGRANAJE DEFECTUOSO",
            "data_digitacao": "17/05/2024",
            "data_conserto": null,
            "consumidor_fone_comercial": null,
            "consumidor_email": "fernando_nakata@hotmail.com",
            "consumidor_endereco": "5 de Abril",
            "consumidor_numero": "1233",
            "consumidor_bairro": "",
            "consumidor_complemento": "",
            "consumidor_cep": "",
            "consumidor_cidade": "VINA DEL MAR",
            "consumidor_estado": "VA",
            "data_fechamento": null,
            "os_reincidente": null,
            "referencia": "DUC252",
            "descricao": "ATORNILLADOR DE IMPACTO INALAMBRICO 18V S/BATERIA",
            "serie": "SERIE900",
            "data_fabricacao": null,
            "defeito_reclamado": "PERDIDAD DE POTENCIA",
            "defeito_constatado": null,
            "solucao": null,
            "consumidor_nome": "FERNANDO TELECONTROL",
            "consumidor_fone": "",
            "consumidor_cpf": "95370217",
            "revenda": "RENATO DIAZ SA",
            "nota_fiscal": "6666666666",
            "data_nf": "01/12/2023",
            "status_os": "Aguardando Peças",
            "local_reparo": null,
            "dias_aberto": 6,
            "hd_chamado": null,
            "data_atendimento_callcenter_resolvido": null,
            "data_abertura_atendimento": null,
            "idPedido": 49091287,
            "direccion": "SANTA ROSA 1508-1510"
        }
    ],

    response: {
        "osIngresadas": [],
        "osNoIngresadas": [66284230,66284231]
    }
    

   }
   
};